# Generated by Django 4.2 on 2023-04-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slag',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
